def find_motif(haystack, needle):
    res = []
    for i in xrange(len(haystack) - len(needle)):
        found = True
        for j in xrange(len(needle)):
            if haystack[i + j] != needle[j]:
                found = False
                break
        if found:
            res += [i + 1]
    return res

h = 'ACTACGGTAATACGGTAATGTGACCACGGTAACTATACGGTAAACGGTAACAGTCAGGGCTACGGTAATTACGGTAAACGGTAATACGGTAAACACGGTAACATAACAGACGGTAATAACGGTAAACGGTAATCACGGTAAAAACGGTAACAACGGTAACACGGTAACTGCACTCGTAACTACGGTAATACGGTAAGACGGTAAACGGTAACACGGTAAACGGTAATACGGTAACAGTACGGTAACAGGATAACGGTAACACGGTAAAGGCTCCGGACGGTAAGACGGTAAAACGGTAATGACGGTAAGTCCTACGGTAAAGACGCACGGTAATACGGTAAGTGACGGTAAACGGTAAACGGTAACTGGCTGACGGTAAACGGTAAAGGACGGTAAACGGTAATACGGTAATCTGATATGACAAACGGTAAAACGGTAAACGGTAACTCACGGTAATTTCACGGTAAGACGGTAACACGGTAACATCGACGGTAAGACGGTAAAGACGGTAAACGGTAATGATACGGTAAGACGGTAACGTTACGGTAACTTTTGGATAGGTCCACACGGTAACCCACGGTAATTCCCACGGTAAGAACGGTAACACGGTAATGGAACGGTAAGACGGTAATACGGTAATAAGTACGGTAAGCACGGTAAACGGTAACCCTATACGACGGTAACCACGGTAAAGACGGTAACCACGGTAACGACACGGTAACTACGGTAAAAGATCTACGGTAAACGGTAACTACGGTAAGACGGTAAGTAACGGTAACACGGTAATTTGAACGGTAACGGACGGTAAACGGTAATAGAGACGGTAA'
n = 'ACGGTAAAC'
print ' '.join(map(str, find_motif(h,n)))
